### ISSUE TITLE
Symfony3 support

### ISSUE THREAD

**Issue by Irvyne** [knpuniversity/KnpUGuard#15]
Hi all, are you agree if we update the composer.json to add symfony3 support ?

```
"require": {
    "php": ">=5.3.9",
    "symfony/security-core": "~2.6|~3.0",
    "symfony/security-http": "~2.6|~3.0"
},
```

If you agree KnpUGuardBundle have to be updated too.

```
"require": {
    "php":                          ">=5.3.9",
    "knpuniversity/guard":          "~0.1",
    "symfony/framework-bundle":     "~2.3|~3.0",
    "symfony/security-bundle":      "~2.6|~3.0"
},
```

**Comment by weaverryan** [comment]
Hi @Irvyne!

I'm a _maybe_ on this. Well, we probably should do this - but why not just use the official Guard component once you're on Symfony 2.8?

**Comment by Irvyne** [comment]
Hi @weaverryan!

You are right but it means that developers have to pass by symfony 2.8 to use the official Guard component and after using the official component pass to symfony 3.0. 
It seems to make sense to me even if the "bad" possibility of using it on symfony 3 could be good (for lazy ones).
Are you agree if the README explain clearly on the beginning that people using the lib/bundle have to pass by symfony 2.8 to use the official component before trying to pass to symfony 3 ?

**Comment by weaverryan** [comment]
@Irvyne Developers will already need to go to 2.8 first, then change some of their code before going to 3.0. That's because some features are only deprecated in 2.8 (so you need to upgrade to 2.8 in order to get access to the "new" way of doing something).

But, I really don't see any harm, and we need to update the README anyways to mention that this library is deprecated and you should switch to the true library in 2.8.

You don't have a few minutes to make these changes by chance, do you? 

Thanks!

**Comment by Irvyne** [comment]
@weaverryan I have time, I'll do that this weekend. Thanks for your super work :+1:

**Comment by weaverryan** [comment]
Thank you :) - it's a very busy time in the Symfony-world - we need all the help we can get!

**Comment by Irvyne** [comment]
Hi @weaverryan sorry for the delay, I've created the pull request, do you want I do the same for KnpUGuardBundle ?

**Comment by weaverryan** [comment]
I saw the PR - having one for KnpUGuardBundle also would be awesome. I was also thinking we should explain a few of the differences - like a before (with KnpUGuard) and after (with Symfony 2.8 Guard) code example - to help people know what to expect when upgrading. You don't have to do that, but if it seems easy to you, awesome!

**Comment by Irvyne** [comment]
I've added some "example" code. This seems to be good?

**Comment by weaverryan** [comment]
Yes, it looks very good :). So, I think we can close this now?

**Comment by Irvyne** [comment]
Yes, thank you :-)
