### ISSUE TITLE
Tutorial request - Possibility with two-step authentication?

### ISSUE THREAD

**Issue by Richard87** [knpuniversity/KnpUGuard#16]
Hi!

I have been looking at a good way to enable two-step/factor authentication with symfony (username and password in step 1, and a SMS for step 2)...

Can this be solved in KnpUGuard?

Thanks, Richard

**Comment by weaverryan** [comment]
@Richard87 I've heard this question a few times, we should indeed add a tutorial about it for KnpUniversity. I haven't tried this yet, but I would do this:

1) During username/password, create a new exception class that extends AuthenticationException - e.g. `RequiresSecondStepAuthenticationException`. Throw this in `checkCredentials()` if everything looks good.

2) In `onAuthenticationFailure`, look for this exact exception. If you find it, store anything you need in the session (like the user id), and redirect to the SMS step.

3) Have a second authenticator that handles the SMS authentication. Of course, it will look in the session for details stored in step (2) to make sure that the first authenticator finished its job.

So my current thought is: have 2 authenticators, but one is always designed to "fail" and pass off to the second authenticator. I'll likely use this same approach for "social login" where you need to redirect the user to some "finish registration" page before actually authenticating them.

**Comment by Richard87** [comment]
Alright! Thanks for that, I'll take a look at this strategy :)
