### ISSUE TITLE
How to logout?

### ISSUE THREAD

**Issue by mathewpeterson** [knpuniversity/KnpUGuard#8]
I am trying to use this for a new project and I believe I have everything working except for the ability to log out. Does Guard handle that or should I implement that manually?

Thank you!

**Comment by bocharsky-bw** [comment]
I think **logging out** already realized in Symfony [Security](http://symfony.com/doc/current/book/security.html) component. You should easily to define `logout` in your firewall, check the [docs](http://symfony.com/doc/current/book/security.html#logging-out) please.

**Comment by weaverryan** [comment]
@bocharsky-bw is exactly right - you'll handle logging out exactly like normal. Additionally - things like remember_me and switch_user also work totally like normal :).

If you hit any issues, let me know!

**Comment by mathewpeterson** [comment]
Ah, yes, you are correct. That worked! 

Great job on the library and thanks for the help!
